import tkinter as tk
from tkinter import ttk
class Aplicacion:
    def __init__(self):
        self.ventana=tk.Tk()
        self.crear_botones()
        self.canvas=tk.Canvas(self.ventana, width=760, height=590)
        self.canvas.grid(column=0, row=1)
        fondo= tk.PhotoImage(file="./src/Base_I.png")
        self.canvas.create_image(0, 0, image=fondo, anchor="nw")
        diente1=tk.PhotoImage(file="./src/TercerMolar_I_I.png")
        self.canvas.create_image(48, 23, image=diente1, anchor="nw")
        diente2=tk.PhotoImage(file="./src/SegundoMolar_I_I.png")
        self.canvas.create_image(48, 123, image=diente2, anchor="nw")
        diente3=tk.PhotoImage(file="./src/PrimerMolar_I_I.png")
        self.canvas.create_image(48, 223, image=diente3, anchor="nw")
        diente4=tk.PhotoImage(file="./src/SegundoPreMolar_I_I.png")
        self.canvas.create_image(73, 323, image=diente4, anchor="nw")
        diente5=tk.PhotoImage(file="./src/PrimerPreMolar_I_I.png")
        self.canvas.create_image(120, 400, image=diente5, anchor="nw")
        diente6=tk.PhotoImage(file="./src/Canino_I_I.png")
        self.canvas.create_image(175, 460, image=diente6, anchor="nw")
        diente7=tk.PhotoImage(file="./src/IncisivoLateral_I_I.png")
        self.canvas.create_image(240, 477, image=diente7, anchor="nw")
        diente8=tk.PhotoImage(file="./src/IncisivoCentral_I_I.png")
        self.canvas.create_image(285, 477, image=diente8, anchor="nw")
        diente9=tk.PhotoImage(file="./src/IncisivoCentral_D_I.png")
        self.canvas.create_image(335, 485, image=diente9, anchor="nw")
        diente10=tk.PhotoImage(file="./src/IncisivoLateral_D_I.png")
        self.canvas.create_image(405, 460, image=diente10, anchor="nw")
        diente11=tk.PhotoImage(file="./src/Canino_D_I.png")
        self.canvas.create_image(450, 450, image=diente11, anchor="nw")
        diente12=tk.PhotoImage(file="./src/PrimerPreMolar_D_I.png")
        self.canvas.create_image(510, 400, image=diente12, anchor="nw")
        diente13=tk.PhotoImage(file="./src/SegundoPreMolar_D_I.png")
        self.canvas.create_image(521, 322, image=diente13, anchor="nw")
        diente14=tk.PhotoImage(file="./src/PrimerMolar_D_I.png")
        self.canvas.create_image(546, 223, image=diente14, anchor="nw")
        diente15=tk.PhotoImage(file="./src/SegundoMolar_D_I.png")
        self.canvas.create_image(550, 115, image=diente15, anchor="nw")
        diente16=tk.PhotoImage(file="./src/TercerMolar_D_I.png")
        self.canvas.create_image(552, 18, image=diente16, anchor="nw", tag="diente16")
        self.ventana.mainloop()
       
    def crear_botones(self):
        self.labelframe=ttk.LabelFrame(self.ventana,text="Opciones")
        self.labelframe.grid(column=1, row=0, sticky="w", padx=5, pady=5)
        self.boton1=ttk.Button(self.labelframe, text="Borrar", command=self.borrar_linea)
        self.boton1.grid(column=0, row=0, padx=5) 

    def borrar_linea(self):
        self.canvas.delete("diente16")

aplicacion=Aplicacion()